Pin alpine version to match Pipfile
Currently running the docker image fails with 'ImportError: cannot import name 'Mapping' from 'collections'' due to pulling down the latest version of Python from alpine. 

If we pinning to the version specified in the Pipfile, it resolves it.